- src/components/Paper/Paper.md
- src/components/Paper/Paper.tsx
- src/theme/theme.ts
- styleguide.config.js
> Add Paper component

- .github/workflows/main.yml
- package.json
- tsconfig.json
Adds github actions to run build and test commands on PRs and commits to master
> DEV-22 Create basic CI

- .storybook/preview-head.html
- src/components/PaginationItem/PaginationItem.tsx
- src/theme/theme.ts
- styleguide.config.js
- Added font imports
- Added typography variants
> DEV-23: Add fonts

- src/components/Paper/Paper.md
- src/components/Paper/Paper.stories.tsx
- src/components/Paper/Paper.tsx
- Fixed elevation border styles
- Added higher elevation (2)
> DEV-18: Updated elevations

- .storybook/preview.js
- docs/index.md
- src/theme/ThemeWrapper.tsx
- styleguide.config.js
- Moved the responsibility of importing normalize.css to the library user
- Added usage warning about it
- Added normalize.css import to storybook and styleguidist
> Refactor normalize css

- package.json
- yarn.lock
Added resolution to babel-loader version, tests were not running because of different versions
> Fix babel version

- src/components/Popover/Popover.tsx
- src/helpers/ssr.ts
Fixed usage of `document` for SSR environments
> Fix Popover in SSR

- src/components/Selector/Selector.tsx
Changed open styles as per design team's request
> DEV-84: Changed open styles

- src/components/EditableText/EditableTest.test.tsx
- src/components/EditableText/EditableText.md
- src/components/EditableText/EditableText.stories.tsx
- src/components/EditableText/EditableText.tsx
- src/components/ValueList/ValueList.tsx
- Changed `EditableText` component to be controlled only, so that input-masks can be more easily integrated into it
- Adjusted `ValueList` component paddings and sizes
> DEV-72 - EditableText and ValueList changes

- src/components/Popover/Popover.tsx
Fixes bug shown here: https://www.screencast.com/t/33QenkRSHhzX
> fix(Popover): Fixed popover overlay bug

- src/components/Autocomplete/Autocomplete.tsx
- src/components/Popover/Popover.tsx
- src/components/Select/Select.tsx
- src/components/SubNavigationMenu/SubNavigationMenu.tsx
Also 
- Fixed Autocomplete keyboard navigation not working
- Fixed storybook dev error with jsx import
> fix(Popover): Fixed popover clipping on rare cases DEV-296

- package.json
- yarn.lock
Tested in back-office and works as expected
> breaking: moved theme-ui to peerDependencies STC-403

- src/components/Button/Button.tsx
- src/components/FloatingCard/FloatingCard.tsx
- src/components/TextField/TextField.tsx
Added some changes to better control form submits, to address some issues in the accounts app in the login form
fix(Button): changed default type to button
feat(FloatingCard): Added appendTo prop
feat(TextField): Added form prop to be passed to input
> Minor fixes for forms

- package.json
- src/components/Popover/LazyTippy.tsx
- src/components/Popover/Popover.tsx
- src/components/Select/Select.tsx
Fixed non-focusing when Tab key was pressed.
Fixed the non-navigation through the select options with keyboard arrows.
> fix(Select): Fixes a11y issues STC-786

- src/components/MobileModal/MobileModal.tsx
Fixed closing Modal when typed on input field using a draggable MobileModal
> fix(MobileModal): Fixes closing when input STC-794

- docs/index.md
- plop-templates/docs/component.hbs
- website/docs/components/Accordion.mdx
- website/docs/components/Button.mdx
- website/docs/components/Card.mdx
- website/docs/components/Divider.mdx
- website/package.json
- website/yarn.lock
- Added Accordion docs
- Reworked docs and plop template to follow the same pattern and look kind of the same when navigating between each one
> docs: Added Accordion docs STC-732

- styleguide.config.js
- Updates CDN link, only
DHP-1402
> DHP-1402 / Updates CDN link

- package.json
Updates package version only
dhp-1401 -
> dhp-1401 - Updates package version only

- .storybook/preview-head.html
- package.json
- website/src/theme/Root.js
Updates more cdn links
Updates more cdn links
> DHP-1729 / Updates more cdn links

- .github/workflows/release.yml
Adds release.yml to publish in npm
DHP-1735
> DHP-1735 / Adds release.yml to publish in npm

- package.json
- src/components/DateSelect/DateSelect.test.tsx
- src/components/DateSelect/DateSelect.tsx
- src/components/Select/Select.test.tsx
- src/components/Select/Select.tsx
- src/components/Select/SelectOptionCustom.tsx
Hotfix to translate datepicker. Herzui doesnt have i18n, we will need in the future pass it as a prop or create a exported context.
> DHP-1929/Translate select & datepicker

- package.json
- src/components/Snackbar/Snackbar.md
- src/components/Snackbar/Snackbar.tsx
> dhp-2099 / Custom toast

- package.json
- src/components/PlusLabel/PlusLabel.md
- src/components/PlusLabel/PlusLabel.tsx
- src/components/index.ts
> DHP-2103/Adds PlusLabel

- package.json
- src/components/Snackbar/Snackbar.md
- src/components/Snackbar/Snackbar.tsx
- src/components/Snackbar/context/SnackbarContext.ts
- src/components/Snackbar/context/SnackbarItem.tsx
- src/components/Snackbar/context/SnackbarProvider.tsx
- styleguide.config.js
Updates Herz UI to V2 + Adds snackbar animation:
> Updates V2
